[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU",
	".*"
]

[[custom_groups]]
name = "proxy"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
	"[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸ“ºYouTube"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU"
]

[[custom_groups]]
name = "Google"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸ¤–GPT"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸŒ TikTok"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸš©æ¸¯å°",
    "[]ğŸš©æ—¥éŸ©",
    "[]ğŸš©ç¾å›½",
    "[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
    "[]âœˆMOJIE",
    "[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸš©æ¸¯å°",
    "[]ğŸš©æ—¥éŸ©",
    "[]ğŸš©ç¾å›½",
    "[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
    "[]âœˆMOJIE",
    "[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸ¥ NETFLIX"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
	"[]ğŸš©æ¸¯å°",
	"[]ğŸš©æ—¥éŸ©",
	"[]ğŸš©ç¾å›½",
	"[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
	"[]âœˆMOJIE",
	"[]âœˆGAOSU"
]

[[custom_groups]]
name = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = [
	"[]ğŸ›‘ å…¨çƒæ‹¦æˆª",
	"[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
]

[[custom_groups]]
name = "ğŸš« è¿è¥åŠ«æŒ"
type = "select"
rule = [
	"[]ğŸ›‘ å…¨çƒæ‹¦æˆª",
	"[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
]


[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = [
	"[]ğŸ¯ å…¨çƒç›´è¿",
	"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = [
	"[]ğŸ¯ å…¨çƒç›´è¿",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸš©æ¸¯å°",
    "[]ğŸš©æ—¥éŸ©",
    "[]ğŸš©ç¾å›½",
    "[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
    "[]âœˆMOJIE",
    "[]âœˆGAOSU"
]


[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥ä¿¡æ¯"
type = "select"
rule = [
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
	"[]ğŸ¯ å…¨çƒç›´è¿",
    "[]ğŸš©æ¸¯å°",
    "[]ğŸš©æ—¥éŸ©",
    "[]ğŸš©ç¾å›½",
    "[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
    "[]âœˆMOJIE",
    "[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = [
	"[]ğŸ¯ å…¨çƒç›´è¿",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
	"[]âœ…Fallback",
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]ğŸš©æ¸¯å°",
    "[]ğŸš©æ—¥éŸ©",
    "[]ğŸš©ç¾å›½",
    "[]ğŸš©äºšå¤ª",
	"[]âœˆTAISHAN",
    "[]âœˆMOJIE",
    "[]âœˆGAOSU"
]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = [
	"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
	"[]ğŸ¯ å…¨çƒç›´è¿",
	"[]âœ…Fallback",
	"[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "âœ…Fallback"
type = "fallback"
rule = ["[]GAOSUAUTO", "[]MOJIEAUTO", "[]TAISHANAUTO"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸš©æ¸¯å°"
type = "select"
rule = ["[]æ¸¯å°AUTO", "é¦™æ¸¯", "HK", "å°æ¹¾", "TW"]

[[custom_groups]]
name = "ğŸš©æ—¥éŸ©"
type = "select"
rule = ["[]æ—¥éŸ©AUTO", "æ—¥æœ¬", "JP", "éŸ©å›½"]

[[custom_groups]]
name = "ğŸš©ç¾å›½"
type = "select"
rule = ["[]ç¾å›½AUTO", "ç¾å›½", "US"]

[[custom_groups]]
name = "ğŸš©äºšå¤ª"
type = "select"
rule = ["[]äºšå¤ªAUTO", "æ–°åŠ å¡", "è¶Šå—", "è²å¾‹å®¾", "å°åº¦"]

[[custom_groups]]
name = "âœˆMOJIE"
type = "select"
rule = ["[]MOJIEAUTO", "!!GROUP=mojie"]

[[custom_groups]]
name = "âœˆGAOSU"
type = "select"
rule = ["[]GAOSUAUTO", "!!GROUP=gaosu"]

[[custom_groups]]
name = "âœˆTAISHAN"
type = "select"
rule = ["[]TAISHANAUTO", "!!GROUP=taishan"]

[[custom_groups]]
name = "TAISHANAUTO"
type = "url-test"
rule = ["!!GROUP=taishan"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "MOJIEAUTO"
type = "url-test"
rule = ["!!GROUP=mojie"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "GAOSUAUTO"
type = "url-test"
rule = ["!!GROUP=gaosu"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "æ¸¯å°AUTO"
rule = ["é¦™æ¸¯", "HK", "å°æ¹¾", "TW"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "æ—¥éŸ©AUTO"
rule = ["æ—¥æœ¬", "JP", "éŸ©å›½"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "ç¾å›½AUTO"
rule = ["ç¾å›½", "US"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false

[[custom_groups]]
name = "äºšå¤ªAUTO"
rule = ["æ–°åŠ å¡", "è¶Šå—", "è²å¾‹å®¾", "å°åº¦"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50
lazy = false
